### ISSUE TITLE
Flatpak serial device access.

### ISSUE THREAD

**Issue by leamas** [openplotter/openplotter-serial#6]
Just a drive-by note: Using serial devices from Flatpak requires some udev rules support. I havn't looked into if you are handling it elsewhere, but otherwise this seems like having the infrastructure in place.

Documentation: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak#flatpak_access_to_serial_devices
and https://github.com/OpenCPN/OpenCPN/blob/master/LINUX_DEVICES.md

**Comment by sailoog** [comment]
closed by https://github.com/openplotter/openplotter-serial/commit/dafb0fc598002fa70fa79b4cff2a4939af6c046a
thanks
